### ISSUE TITLE
Breadth First Search Algorithm

### ISSUE THREAD

**Issue by yaranathakur** [devs2gather/algorithms#17]
# Breadth First Search Algorithm
I want to contribute to above mentioned algorithm with python.

**Comment by yaranathakur** [comment]
@PradyumnaKrishna
Please assign me with this algorithm.

**Comment by PradyumnaKrishna** [comment]
Assigned @yaranathakur

**Comment by yaranathakur** [comment]
Thank You @PradyumnaKrishna
