### ISSUE TITLE
Infix to Postfix Conversion using Stack

### ISSUE THREAD

**Issue by AnchalSingh20** [devs2gather/algorithms#24]
Want to contribute a C program for converting Infix expression to Postfix  expression.

**Infix** - An infix operation is any operation of the format x op y format, such as x + y.

**Postfix** - An operation or expression can also be expressed as x y op, i.e. x y +, which is equivalent to writing x + y in infix. All we're trying to perform relocating the operator to the operand's right.

**Comment by PradyumnaKrishna** [comment]
Go ahead @AnchalSingh20 and contribute.

**Comment by PradyumnaKrishna** [comment]
Closed with #35
