### ISSUE TITLE
vector drawing on canvas

### ISSUE THREAD

**Issue by Rajveer07** [devs2gather/algorithms#6]
I want to write a code for drawing vectors on HTML canvas , using javascript with no external libraries

**Comment by PradyumnaKrishna** [comment]
Sorry @Rajveer07, I forgot to mention, you can only contribute to only one issue to this repository.

**Comment by pennyvice** [comment]
Can you explain me the issue elaboratory @PradyumnaKrishna  bhaiya

**Comment by PradyumnaKrishna** [comment]
> Can you explain me the issue elaboratory @PradyumnaKrishna bhaiya

No need to work on this issue. Closing as you both already contributed to this repository.
