### ISSUE TITLE
Bubble Sort Algorithm

### ISSUE THREAD

**Issue by TheShivamkumarsingh** [devs2gather/algorithms#9]
I want to add searching algorithms by using java language (Linear Search)

**Comment by PradyumnaKrishna** [comment]
Linear search is already taken by #3. You are welcome to contribute another algorithm.

**Comment by TheShivamkumarsingh** [comment]
Then I want to add bubble sort

**Comment by TheShivamkumarsingh** [comment]
please assign me that

**Comment by PradyumnaKrishna** [comment]
Go ahead and contribute your work @ShivamBHU
